import {useEffect,useState} from 'react';
import {Action,Busy,Card,Field,Notice} from '../driver/components/ui';
import {record,id} from '../backend/http';
import {point,type Point} from '../backend/clients';
import {useCustomer,useCustomerSession} from './provider';
import {RideMap} from '../map/ride-map';
import {Avatar} from '../ui/avatar';
interface Place extends Point {id:string;label:string;addressText:string;isDefault:boolean}
function places(value:unknown):Place[]{if(!Array.isArray(value))throw Error('INVALID_RESPONSE');return value.map(v=>{const p=record(v);if(typeof p.label!=='string'||typeof p.addressText!=='string'||typeof p.isDefault!=='boolean')throw Error('INVALID_RESPONSE');return {...point(p),id:id(p.id),label:p.label,addressText:p.addressText,isDefault:p.isDefault}})}
export function CustomerAccount({select}:{select:(p:Point,kind:'pickup'|'destination')=>void}){
  const runtime=useCustomer(),state=useCustomerSession();
  const [avatar,setAvatar]=useState(state.session?.profile.avatarUrl??''),[oldPassword,setOldPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[passwordForm,setPasswordForm]=useState(false);
  const [name,setName]=useState(state.session?.profile.fullName??''),[items,setItems]=useState<Place[]>([]),[label,setLabel]=useState(''),[address,setAddress]=useState(''),[lat,setLat]=useState(''),[lng,setLng]=useState(''),[editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  useEffect(()=>{let disposed=false;void runtime.session.authorized(t=>runtime.user.places(t)).then(v=>{if(!disposed)setItems(places(v))}).catch(e=>{if(!disposed)setMessage(String(e))});return()=>{disposed=true}},[runtime]);
  const run=async(work:()=>Promise<unknown>)=>{setBusy(true);setMessage('');try{await work();await runtime.session.reloadProfile();setItems(places(await runtime.session.authorized(t=>runtime.user.places(t))));setMessage('Đã cập nhật')}catch(e){setMessage(e instanceof Error?e.message:'Không cập nhật được')}finally{setBusy(false)}};
  return <Card><Avatar name={name} url={state.session?.profile.avatarUrl}/><Notice>{state.session?.profile.phoneNumber}</Notice><Field label="Họ tên" value={name} onChangeText={setName}/><Field label="Ảnh đại diện · URL HTTPS (tùy chọn)" value={avatar} onChangeText={setAvatar} autoCapitalize="none" keyboardType="url"/><Action label="Lưu hồ sơ" disabled={busy||!name.trim()} onPress={()=>{void run(()=>runtime.session.authorized(t=>runtime.user.updateProfile(t,{fullName:name.trim(),avatarUrl:avatar.trim()||null})))}}/>
    <Action label="Đổi mật khẩu" variant="secondary" onPress={()=>setPasswordForm(v=>!v)}/>{passwordForm&&<><Field label="Mật khẩu hiện tại" value={oldPassword} onChangeText={setOldPassword} secureTextEntry/><Field label="Mật khẩu mới" value={newPassword} onChangeText={setNewPassword} secureTextEntry/><Action label="Lưu mật khẩu và đăng nhập lại" disabled={busy||!oldPassword||!newPassword} onPress={()=>{setBusy(true);void runtime.session.authorized(t=>runtime.user.changePassword(t,oldPassword,newPassword)).then(()=>runtime.session.logout().catch(()=>{})).catch(e=>{setMessage(String(e));setBusy(false)})}}/></>}
    <Notice>Địa chỉ yêu thích</Notice>
    {items.map(p=><Card key={p.id}><Notice>{p.label} · {p.addressText}{p.isDefault?' · Mặc định':''}</Notice><Action label="Dùng làm điểm đón" disabled={busy} onPress={()=>select(p,'pickup')}/><Action label="Dùng làm điểm đến" disabled={busy} onPress={()=>select(p,'destination')}/><Action label="Sửa địa chỉ" disabled={busy} onPress={()=>{setEditing(p.id);setLabel(p.label);setAddress(p.addressText);setLat(String(p.lat));setLng(String(p.lng))}}/><Action label="Đặt mặc định" disabled={busy||p.isDefault} onPress={()=>{void run(()=>runtime.session.authorized(t=>runtime.user.defaultPlace(t,p.id)))}}/><Action label="Xóa địa chỉ" disabled={busy} onPress={()=>{void run(()=>runtime.session.authorized(t=>runtime.user.deletePlace(t,p.id)))}}/></Card>)}
    <RideMap height={200} onSelect={busy?undefined:p=>{setLat(String(p.lat));setLng(String(p.lng))}}/><Field label="Nhãn địa chỉ" value={label} onChangeText={setLabel}/><Field label="Địa chỉ" value={address} onChangeText={setAddress}/><Field label="Vĩ độ địa chỉ" value={lat} onChangeText={setLat} keyboardType="numbers-and-punctuation"/><Field label="Kinh độ địa chỉ" value={lng} onChangeText={setLng} keyboardType="numbers-and-punctuation"/>
    <Action label={editing?'Lưu địa chỉ đã sửa':'Thêm địa chỉ'} disabled={busy||!label.trim()||!address.trim()||!lat.trim()||!lng.trim()} onPress={()=>{void run(async()=>{const p=point({lat:Number(lat),lng:Number(lng)}),body={label:label.trim(),addressText:address.trim(),lat:p.lat,lng:p.lng,makeDefault:false};await runtime.session.authorized(t=>editing?runtime.user.updatePlace(t,editing,body):runtime.user.createPlace(t,body));setEditing(null);setLabel('');setAddress('');setLat('');setLng('')})}}/>
    {editing&&<Action label="Dừng sửa" disabled={busy} onPress={()=>setEditing(null)}/>}<Busy visible={busy}/><Notice>{message}</Notice>
  </Card>;
}
