const path = require('node:path');
const root = path.resolve(__dirname, '..');
const images = {
  postgres: 'postgres:18@sha256:5a5a84b19854a9ffaa54082c166ff4ec27473a361e496e5ea167f298f2da9722',
  redis: 'redis:8-alpine@sha256:3811787313eba226a2ef38658c6ccb91cd5e110edc89c37767de373120a0e5a0',
  rabbit: 'rabbitmq:4-management@sha256:8dd6e3570ddaa2ef82a6c3a8950e79c1f73893adfbdddbc374fc1f1ac8a0f5dd',
  osrm: 'chande-osrm:local', nginx: 'nginx:stable-alpine@sha256:0985e772fb9f729e6fa0980da05fca5d9c468e870eed43071545afa9d2e27d94',
};
function stack(s) {
  const app = (service, port, env, extra = {}) => ({ service, port, image: `chande-backend-${service}:local`, env, ready: '/health/ready', live: '/health/live', ...extra });
  const db = name => `postgres://${name}_service:${s[name + 'Password']}@postgres:5432/${name}_db`;
  const trip = { NODE_ENV: 'development', INTEGRATION_MODE: 'real', DATABASE_URL: db('trip'), SUPPORTED_VEHICLE_TYPES: 'CAR_4,CAR_7', AUTH_JWKS_URL: 'http://user-api:3011/.well-known/jwks.json', AUTH_JWT_ISSUER: 'chande-rider-local', AUTH_JWT_AUDIENCE: 'trip-service', DRIVER_AUTH_JWKS_URL: 'http://driver-api:3003/.well-known/jwks.json', DRIVER_AUTH_JWT_ISSUER: 'chande-driver-local', CURSOR_SIGNING_KEY: s.cursor, MATCHING_CALLBACK_TOKEN: s.matchingTrip, DRIVER_LOOKUP_TOKEN: s.driverTrip, ROUTING_BASE_URL: 'http://routing-api:3004', PRICING_BASE_URL: 'http://price-api:3005', MATCHING_BASE_URL: 'http://matching-api:3007', GATEWAY_EVENTS_BASE_URL: 'http://gateway-api:8090', NOTIFICATION_BASE_URL: 'http://gateway-api:8090', ROUTING_TOKEN: s.tripRouting, PRICING_TOKEN: s.tripPrice, MATCHING_TOKEN: s.tripMatching, GATEWAY_EVENTS_TOKEN: s.tripGateway, NOTIFICATION_TOKEN: s.tripGateway, SWAGGER_ENABLED: 'false' };
  const matching = { HOST: '0.0.0.0', NODE_ENV: 'development', DATABASE_URL: db('matching'), RABBITMQ_URL: `amqp://backend:${s.rabbitPassword}@rabbitmq:5672`, MATCHING_TRIP_TOKEN: s.tripMatching, MATCHING_DRIVER_TOKEN: s.driverMatching, MATCHING_REALTIME_TOKEN: s.realtimeMatching, ROUTING_BASE_URL: 'http://routing-api:3004', ROUTING_MATCHING_TOKEN: s.matchingRouting, DRIVER_BASE_URL: 'http://driver-api:3003', DRIVER_MATCHING_TOKEN: s.matchingDriver, TRIP_BASE_URL: 'http://trip-api:3001', TRIP_MATCHING_TOKEN: s.matchingTrip, AUTH_JWKS_URL: 'http://driver-api:3003/.well-known/jwks.json', AUTH_JWT_ISSUER: 'chande-driver-local', AUTH_JWT_AUDIENCE: 'matching-service' };
  return {
    'user-api': app('user', 3011, { PORT: '3011', DB_URL: 'jdbc:postgresql://postgres:5432/user_db', DB_USERNAME: 'user_service', DB_PASSWORD: s.userPassword, JWT_ISSUER: 'chande-rider-local', JWT_PRIVATE_KEY_FILE: '/run/keys/user.pem', JWT_KEY_ID: 'backend-rider-v1', JWT_AUDIENCE: 'trip-service', INTERNAL_API_KEY: s.userInternal }, { ready: '/health', live: '/health', keys: true, java: true }),
    'gateway-api': app('gateway', 8080, { PORT: '8080', INTERNAL_PORT: '8090', USER_SERVICE_URLS: 'http://user-api:3011', DRIVER_SERVICE_URLS: 'http://driver-api:3003', TRIP_SERVICE_URLS: 'http://trip-api:3001', ROUTING_SERVICE_URLS: 'http://routing-api:3004', MATCHING_SERVICE_URLS: 'http://matching-api:3007', ROUTING_GATEWAY_TOKEN: s.gatewayRouting, RIDER_JWT_ISSUER: 'chande-rider-local', RIDER_JWKS_URI: 'http://user-api:3011/.well-known/jwks.json', DRIVER_JWT_ISSUER: 'chande-driver-local', DRIVER_JWKS_URI: 'http://driver-api:3003/.well-known/jwks.json', TRIP_SERVICE_TOKEN: s.tripGateway, REDIS_HOST: 'redis', REDIS_PORT: '6379', SPRING_DATA_REDIS_DATABASE: '3', AUTH_MAX_ATTEMPTS: '30', CORS_ALLOWED_ORIGINS: 'http://localhost:5500,http://127.0.0.1:5500,http://localhost:8081,http://127.0.0.1:8081' }, { ready: '/actuator/health/readiness', live: '/actuator/health/liveness', java: true }),
    'driver-api': app('driver', 3003, { NODE_ENV: 'development', PORT: '3003', DATABASE_URL: db('driver'), REDIS_URL: 'redis://redis:6379/1', AUTH_JWT_ISSUER: 'chande-driver-local', AUTH_JWT_AUDIENCES: 'driver-service,trip-service,realtime-service,matching-service', AUTH_SIGNING_KEY_FILE: '/run/keys/driver.pem', AUTH_KEY_ID: 'backend-driver-v1', OTP_MODE: 'mock', OTP_MOCK_CODE: '123456', OTP_RESEND_SECONDS: '1', TRIP_MODE: 'real', TRIP_BASE_URL: 'http://trip-api:3001', HTTP_TIMEOUT_MS: '2000', MATCHING_INBOUND_TOKEN: s.matchingDriver, REALTIME_INBOUND_TOKEN: s.realtimeDriver, TRIP_LOOKUP_TOKEN: s.driverTrip, MATCHING_LOOKUP_TOKEN: s.driverMatching, MATCHING_BASE_URL: 'http://matching-api:3007' }, { keys: true }),
    'trip-api': app('trip', 3001, trip, { migration: true }),
    'trip-worker': app('trip', 3002, trip, { command: ['node', 'dist/worker.js'], worker: true, dependencies: ['trip-api'] }),
    'routing-api': app('routing', 3004, { NODE_ENV: 'development', APP_ENV: 'development', HOST: '0.0.0.0', PORT: '3004', INTEGRATION_MODE: 'real', REALTIME_INTEGRATION_MODE: 'real', REALTIME_BASE_URL: 'http://realtime-api:3006', REALTIME_TOKEN: s.routingRealtime, REALTIME_TIMEOUT_MS: '3000', MATRIX_MAX_CANDIDATES: '50', SUPPORTED_VEHICLE_TYPES: 'CAR_4,CAR_7', VEHICLE_PROFILES_FILE: 'config/vehicle-profiles.osrm.json', EXTERNAL_MAP_BASE_URL: 'http://osrm:5000', EXTERNAL_MAP_ALLOW_HTTP: 'true', EXTERNAL_MAP_ALLOWED_HOSTS: 'osrm', ROUTING_TRIP_TOKEN: s.tripRouting, ROUTING_MATCHING_TOKEN: s.matchingRouting, ROUTING_GATEWAY_TOKEN: s.gatewayRouting }),
    'price-api': app('price', 3005, { NODE_ENV: 'development', HOST: '0.0.0.0', PRICE_TRIP_TOKEN: s.tripPrice, SUPPORTED_VEHICLE_TYPES: 'CAR_4,CAR_7', FARE_POLICY_FILE: 'config/fare-policy.example.json' }),
    'matching-api': app('matching', 3007, matching, { migration: true }),
    'matching-worker': app('matching', 3017, matching, { command: ['node', 'dist/worker.js'], worker: true, dependencies: ['matching-api', 'trip-api', 'routing-api', 'realtime-api'] }),
    'realtime-api': app('realtime', 3006, { NODE_ENV: 'development', PORT: '3006', REDIS_URL: 'redis://redis:6379/2', AUTH_JWKS_URL: 'http://driver-api:3003/.well-known/jwks.json', AUTH_JWT_ISSUER: 'chande-driver-local', AUTH_JWT_AUDIENCE: 'realtime-service', DRIVER_BASE_URL: 'http://driver-api:3003', DRIVER_TIMEOUT_MS: '2500', ROUTING_INBOUND_TOKEN: s.routingRealtime, DRIVER_ELIGIBILITY_TOKEN: s.realtimeDriver, RABBITMQ_URL: matching.RABBITMQ_URL, MATCHING_BASE_URL: 'http://matching-api:3007', MATCHING_REALTIME_TOKEN: s.realtimeMatching }),
  };
}
module.exports = { root, images, stack };
