import type {PropsWithChildren} from 'react';
import {Text,View,Pressable,StyleSheet} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
export const palette={primary:'#00685f',container:'#e4f8f3',ink:'#0b1c30',muted:'#647574',surface:'#f8f9ff',card:'#ffffff',line:'#dfe9e7',danger:'#ba1a1a'};
export function Logo({driver=false}:{driver?:boolean}){return <View style={styles.logoRow}><View style={styles.logo}><Ionicons name="flash" size={26} color="white"/></View><View><Text style={styles.brand}>VELOX</Text><Text style={styles.tag}>{driver?'Đối tác tài xế':'Chuyến đi của bạn'}</Text></View></View>}
export function Chip({children,tone='default'}:PropsWithChildren<{tone?:'default'|'warning'|'danger'}>){return <View style={[styles.chip,tone==='warning'&&{backgroundColor:'#fff3d6'},tone==='danger'&&{backgroundColor:'#ffdad6'}]}><Text style={[styles.chipText,tone==='danger'&&{color:palette.danger}]}>{children}</Text></View>}
export function Tabs({items,value,onChange}:{items:{key:string;label:string;icon:React.ComponentProps<typeof Ionicons>['name']}[];value:string;onChange:(value:string)=>void}){return <View style={styles.tabs}>{items.map(i=><Pressable accessibilityRole="tab" accessibilityState={{selected:value===i.key}} key={i.key} onPress={()=>onChange(i.key)} style={styles.tab}><Ionicons size={22} name={i.icon} color={value===i.key?palette.primary:palette.muted}/><Text style={[styles.tabText,value===i.key&&{color:palette.primary}]}>{i.label}</Text>{value===i.key&&<View style={styles.dot}/>}</Pressable>)}</View>}
export function vnd(amount:string){if(!/^\d+$/.test(amount))return '—';return amount.replace(/\B(?=(\d{3})+(?!\d))/g,'.')+' ₫'}
export function distance(meters:number){return meters<1000?`${Math.round(meters)} m`:`${(meters/1000).toFixed(1)} km`}
export function duration(seconds:number){return `${Math.max(1,Math.ceil(seconds/60))} phút`}
const styles=StyleSheet.create({logoRow:{flexDirection:'row',alignItems:'center',gap:10},logo:{backgroundColor:palette.primary,width:42,height:42,borderRadius:14,alignItems:'center',justifyContent:'center'},brand:{color:palette.primary,fontFamily:'Inter_700Bold',fontSize:13,letterSpacing:2},tag:{color:palette.ink,fontFamily:'Inter_600SemiBold',fontSize:13},chip:{alignSelf:'flex-start',paddingVertical:7,paddingHorizontal:12,borderRadius:20,backgroundColor:palette.container},chipText:{fontFamily:'Inter_600SemiBold',color:palette.primary,fontSize:12},tabs:{flexDirection:'row',backgroundColor:palette.card,borderTopWidth:1,borderTopColor:palette.line,paddingTop:12,paddingBottom:12},tab:{flex:1,minHeight:48,alignItems:'center',gap:4},tabText:{fontFamily:'Inter_600SemiBold',fontSize:12,color:palette.muted},dot:{height:4,width:4,borderRadius:4,backgroundColor:palette.primary}});
